/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0/userguide/multi_project_builds.html
 */

// FIXME: this is temporary, until we publish common-kotlin-lib
pluginManagement {
    repositories {
        //
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = uri("../local-plugin-repository") 
        }
    }
}

rootProject.name = "decipher"
include(
    "alonzo",
    "ignite",
    "math",
    "pile",
    "reveles",
    "subproject",
    "tools",
    "venturi"
)
