/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.khadga.decipher

import io.kotest.core.spec.style.BehaviorSpec
import io.kotest.matchers.shouldNotBe

class LibraryTest : BehaviorSpec({
    Given("A demo") {
        When("We run it") {
            Then("It passes") {
                true shouldNotBe false
            }
        }
    }
})
