/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.khadga.decipher

import kotlinx.coroutines.*
import kotlinx.coroutines.flow.asFlow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.map
import org.gradle.api.Plugin
import org.gradle.api.Project
import kotlin.random.Random
import kotlin.system.measureTimeMillis

class KotlinLibrary : Plugin<Project> {
    fun someLibraryMethod(): Boolean {
        return true
    }

    override fun apply(target: Project) {
        // figure out how to add kotlin, kapt plugin
        target.pluginManager

        // figure out how to add kotlin coroutine, serialization
        target.dependencies.add("implementation", "")
    }
}

fun simple(): Sequence<Int> = sequence { // sequence builder
    for (i in 1..3) {
        Thread.sleep(1000) // pretend we are computing it
        yield(i) // yield next value
    }
}

suspend fun randomDelay(): Long {
    val delayed = Random.nextLong(1, 5) * 1000
    delay(delayed)
    println("Delayed $delayed millisecond")
    return delayed
}

fun main() = runBlocking {
    val timed = measureTimeMillis {
        val result = coroutineScope {
            listOf(
                async { randomDelay() },
                async { randomDelay() },
                async { randomDelay() }
            ).sumOf {
                // unlike javascript, await() does not block
                it.await()
            }
        }
        println("Result is $result")
    }
    println("Tasks took $timed milliseconds")
}